"""Central place for constants."""

JOURNAL_FILE = "i_ching_journal.csv"

HEXAGRAM_THEME_SUMMARIES = {
    1: "Your journal has recently emphasized creative force, initiative, discipline, and acting with clarity.",
    2: "Your journal has recently emphasized receptivity, patience, support, and allowing things to unfold.",
    3: "Your journal has recently emphasized beginnings, uncertainty, persistence, and finding order through difficulty.",
    4: "Your journal has recently emphasized learning, humility, honest questions, and the patience to be taught.",
    5: "Your journal has recently emphasized waiting, trust, nourishment, and preparing without forcing the moment.",
    6: "Your journal has recently emphasized conflict, boundaries, careful speech, and choosing what is worth contesting.",
    7: "Your journal has recently emphasized discipline, shared purpose, leadership, and organizing energy wisely.",
    8: "Your journal has recently emphasized union, belonging, sincerity, and choosing the right alliances.",
    9: "Your journal has recently emphasized restraint, refinement, small efforts, and the power of gentle influence.",
    10: "Your journal has recently emphasized conduct, courage, tact, and moving carefully through delicate situations.",
    11: "Your journal has recently emphasized harmony, openness, mutual support, and conditions that allow growth.",
    12: "Your journal has recently emphasized obstruction, withdrawal, discernment, and preserving integrity in stagnant times.",
    13: "Your journal has recently emphasized fellowship, shared vision, openness, and meeting others beyond narrow interests.",
    14: "Your journal has recently emphasized abundance, responsibility, generosity, and using strength with grace.",
    15: "Your journal has recently emphasized modesty, balance, quiet confidence, and letting right proportion guide action.",
    16: "Your journal has recently emphasized enthusiasm, momentum, inspiration, and the need to direct energy constructively.",
    17: "Your journal has recently emphasized following, adaptability, trust, and knowing when to respond rather than lead.",
    18: "Your journal has recently emphasized repair, inherited patterns, responsibility, and the courage to correct what has decayed.",
    19: "Your journal has recently emphasized approach, encouragement, growth, and meeting opportunity with care.",
    20: "Your journal has recently emphasized contemplation, perspective, observation, and seeing the larger pattern before acting.",
    21: "Your journal has recently emphasized decisive action, clarity, accountability, and cutting through what blocks truth.",
    22: "Your journal has recently emphasized beauty, simplicity, presentation, and the difference between ornament and substance.",
    23: "Your journal has recently emphasized stripping away, release, endings, and protecting what remains essential.",
    24: "Your journal has recently emphasized return, renewal, recovery, and the quiet reappearance of what matters.",
    25: "Your journal has recently emphasized innocence, naturalness, sincerity, and acting without hidden agenda.",
    26: "Your journal has recently emphasized restraint, stored strength, study, and preparing power before using it.",
    27: "Your journal has recently emphasized nourishment, speech, intake, and choosing what truly sustains you.",
    28: "Your journal has recently emphasized pressure, excess, courageous transition, and the need to rebalance great weight.",
    29: "Your journal has recently emphasized depth, danger, emotional courage, and continuing with integrity through uncertainty.",
    30: "Your journal has recently emphasized clarity, devotion, perception, and tending the light that guides your choices.",
    31: "Your journal has recently emphasized influence, attraction, responsiveness, and the subtle ways people affect one another.",
    32: "Your journal has recently emphasized endurance, consistency, commitment, and sustaining what is worth continuing.",
    33: "Your journal has recently emphasized retreat, timing, boundaries, and stepping back without losing purpose.",
    34: "Your journal has recently emphasized great power, restraint, responsibility, and aligning strength with what is right.",
    35: "Your journal has recently emphasized progress, visibility, recognition, and advancing through steady clarity.",
    36: "Your journal has recently emphasized hidden light, self-protection, patience, and preserving wisdom in difficult conditions.",
    37: "Your journal has recently emphasized family, roles, belonging, and the order created through everyday care.",
    38: "Your journal has recently emphasized difference, tension, individuality, and finding relationship without forced agreement.",
    39: "Your journal has recently emphasized obstacles, humility, help, and choosing the wise path around difficulty.",
    40: "Your journal has recently emphasized release, relief, forgiveness, and loosening what has been held too tightly.",
    41: "Your journal has recently emphasized decrease, simplicity, sacrifice, and discovering what becomes clearer with less.",
    42: "Your journal has recently emphasized increase, generosity, growth, and using favorable energy for meaningful action.",
    43: "Your journal has recently emphasized breakthrough, truth-telling, resolution, and declaring what can no longer be avoided.",
    44: "Your journal has recently emphasized encounter, temptation, vigilance, and recognizing powerful influences early.",
    45: "Your journal has recently emphasized gathering, shared focus, community, and creating a center that can hold people.",
    46: "Your journal has recently emphasized gradual ascent, effort, patience, and progress built step by step.",
    47: "Your journal has recently emphasized limitation, exhaustion, inner resilience, and finding meaning under pressure.",
    48: "Your journal has recently emphasized the well, shared resources, renewal, and returning to a deeper source.",
    49: "Your journal has recently emphasized transformation, renewal, timing, and the courage to change forms.",
    50: "Your journal has recently emphasized the vessel, cultivation, offering, and transforming raw material into nourishment.",
    51: "Your journal has recently emphasized shock, awakening, disruption, and returning to steadiness after impact.",
    52: "Your journal has recently emphasized stillness, boundaries, meditation, and knowing when not to move.",
    53: "Your journal has recently emphasized gradual development, patience, right pacing, and growth that matures over time.",
    54: "Your journal has recently emphasized secondary roles, desire, limits, and finding dignity within imperfect conditions.",
    55: "Your journal has recently emphasized abundance, fullness, decision, and acting while the light is present.",
    56: "Your journal has recently emphasized travel, impermanence, humility, and moving carefully through unfamiliar ground.",
    57: "Your journal has recently emphasized gentle influence, persistence, subtle entry, and shaping change over time.",
    58: "Your journal has recently emphasized joy, exchange, openness, and the nourishment of sincere communication.",
    59: "Your journal has recently emphasized dispersal, release, softening divisions, and letting rigid patterns dissolve.",
    60: "Your journal has recently emphasized limitation, structure, measure, and the freedom created by wise boundaries.",
    61: "Your journal has recently emphasized inner truth, sincerity, trust, and listening beneath surface appearances.",
    62: "Your journal has recently emphasized smallness, attention to detail, humility, and succeeding through careful restraint.",
    63: "Your journal has recently emphasized completion, balance, vigilance, and tending what has already come together.",
    64: "Your journal has recently emphasized incompletion, transition, caution, and the final care needed before arrival.",
}

SAMPLE_QUESTIONS = [
    "What should I understand about my career path right now?",
    "What is the wise next step in my work or professional life?",
    "Where am I being asked to grow, adapt, or hold steady in my career?",
    "What should guide me as I consider this opportunity or transition?",
    "What does this business situation need from me now?",
    "What risk, imbalance, or hidden factor should I pay attention to?",
    "How can I approach this decision with clarity and good timing?",
    "What is the best way to strengthen this project, partnership, or venture?",
    "What should I understand about this relationship dynamic?",
    "How can I respond to this person with clarity and integrity?",
    "What pattern is this relationship asking me to notice?",
    "What boundary, openness, or change may be needed here?",
    "What should guide me as I consider this major life move?",
    "What is changing in my life that I need to honor?",
    "What needs to be completed, released, or prepared before I move forward?",
    "How can I make this decision from a grounded and truthful place?"
]
